name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Run tests
      run: flutter test --no-sound-null-safety || true

    - name: Build APK (Debug)
      run: flutter build apk --debug

    - name: Build APK (Release)
      run: flutter build apk --release

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: sr3h-video-converter-debug
        path: build/app/outputs/flutter-apk/app-debug.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: sr3h-video-converter-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v2.0.1-${{ github.run_number }}
        name: منصة سرعة v2.0.1-${{ github.run_number }}
        body: |
          ## منصة سرعة - تحويل الفيديو إلى 60 إطار
          
          ### الميزات:
          - ✅ تحويل الفيديو إلى 60 إطار في الثانية
          - ✅ نظام تفعيل عبر البريد الإلكتروني
          - ✅ واجهة عربية متجاوبة
          - ✅ فحص متطلبات الفيديو
          - ✅ حفظ في مجلد SR3H
          
          ### التثبيت:
          1. حمل ملف `app-release.apk`
          2. فعل "مصادر غير معروفة" في إعدادات الأمان
          3. ثبت التطبيق
          4. استخدم البريد: `test@example.com` للتجربة
          
          ### متطلبات النظام:
          - Android 5.0 (API 21) أو أحدث
          - مساحة تخزين كافية
          - اتصال بالإنترنت للتفعيل
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/flutter-apk/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}